import type { Metadata } from 'next';
import Image from 'next/image';
import { ExternalLink, Mail } from 'lucide-react';
import { ConversionBand, SiteFooter, SiteHeader } from '@/components/site-frame';
import { siteUrl } from '@/lib/site-content';

export const metadata: Metadata = { title: 'About Transaction Solutions Consulting', description: 'Meet the payment consultants behind TSC and learn how the firm helps businesses improve payment economics, systems, and operations.', alternates: { canonical: `${siteUrl}/about` } };

export default function AboutPage() {
  return <><SiteHeader /><main id="main-content" className="seo-page"><section className="seo-hero about-page-hero"><div><p className="eyebrow">Who TSC is</p><h1>Payment expertise with an owner’s perspective.</h1><p>Transaction Solutions Consulting is an independent payments consulting and brokerage firm based in Gilbert, Arizona and serving businesses nationwide. We help B2B and B2C organizations understand what they pay, how money moves through their operation, and where better technology, qualification, or commercial terms can improve performance.</p></div><aside><span>Our role</span><strong>Make the complex understandable.</strong><p>Protect the client’s interests, coordinate the right resources, and remain useful long after implementation.</p></aside></section><section className="leader-grid"><article id="dan-palmquist"><div className="leader-photo" tabIndex={0}><Image src="/dan-palmquist-optimized.jpg" alt="Dan Palmquist, managing partner of Transaction Solutions Consulting" width={690} height={1000} /><div className="leader-contact"><a href="mailto:dan@transactionsolutionsconsulting.com"><Mail aria-hidden="true" /> Email Dan</a><a href="https://www.linkedin.com/in/dan-palmquist/" target="_blank" rel="noreferrer"><ExternalLink aria-hidden="true" /> LinkedIn</a></div></div><div><p className="eyebrow">Managing partner</p><h2>Dan Palmquist</h2><p>Dan is a B2B payments veteran with more than 30 years of experience helping businesses improve commercial payment acceptance, revenue operations, and financial workflows. His background includes executive roles with TSYS, Global Payments, Paysafe, and Nuvei, where he led partner networks, commercial card programs, and revenue-generating payment initiatives for those organizations.</p></div></article><article id="christian-palmquist"><div className="leader-photo" tabIndex={0}><Image src="/christian-palmquist-optimized.jpg" alt="Christian Palmquist, managing partner of Transaction Solutions Consulting" width={667} height={1000} /><div className="leader-contact"><a href="mailto:christian@transactionsolutionsconsulting.com"><Mail aria-hidden="true" /> Email Christian</a><a href="https://www.linkedin.com/in/christianpalmquist/" target="_blank" rel="noreferrer"><ExternalLink aria-hidden="true" /> LinkedIn</a></div></div><div><p className="eyebrow">Managing partner</p><h2>Christian Palmquist</h2><p>Christian specializes in B2B and B2C payment optimization, helping organizations reduce processing costs, improve cash flow, and streamline payment operations. His expertise spans commercial card acceptance, PCI compliance, Level 2 and Level 3 optimization, ACH solutions, ERP integrations, and practical payment technology strategy.</p></div></article></section><ConversionBand title="Work with an advisor who stays accountable." /></main><SiteFooter /></>;
}
